from tkinter import *
import mysql.connector
import tkinter.messagebox as tm
from functools import partial
def reg():
    base = Tk()
    base.geometry("500x500")
    base.title("registration form")
    name=StringVar()
    lb1= Label(base, text="Enter Name:",width=10, font=("arial",12))
    lb1.place(x=20, y=120)
    en1= Entry(base,textvariable=name)
    en1.place(x=200, y=120)
    lb3= Label(base, text="Enter Email:", width=10, font=("arial",12))
    lb3.place(x=19, y=160)
    mail=StringVar()
    en3= Entry(base,textvariable=mail)
    en3.place(x=200, y=160)
    lb4= Label(base, text="Contact Number:", width=13,font=("arial",12))
    lb4.place(x=19, y=200)
    phno=IntVar()
    en4= Entry(base,textvariable=phno)
    en4.place(x=200, y=200)
    lb5= Label(base, text="Select Gender:", width=15, font=("arial",12))
    lb5.place(x=5, y=240)
    vars = IntVar()
    Radiobutton(base, text="Male", padx=5,variable=vars, value=1).place(x=180, y=240)
    Radiobutton(base, text="Female", padx =10,variable=vars, value=2).place(x=240,y=240)
    Radiobutton(base, text="others", padx=15, variable=vars, value=3).place(x=310,y=240)
    lb2= Label(base, text="Enter username:", width=13,font=("arial",12))
    lb2.place(x=14,y=280)
    user=StringVar()
    en5=Entry(base,textvariable=user)
    en5.place(x=200, y=275)
    lb6= Label(base, text="Enter Password:", width=13,font=("arial",12))
    lb6.place(x=19, y=320)
    passw=StringVar()
    en6= Entry(base,textvariable=passw)
    en6.place(x=200, y=320)
    lb7= Label(base, text="Re-Enter Password:", width=15,font=("arial",12))
    lb7.place(x=21, y=360)
    en7 =Entry(base, show='*')
    en7.place(x=200, y=360)
    register=partial(insert,name,mail,phno,vars,user,passw)
    Button(base, text="Register",command=register, width=10).place(x=200,y=400)
    base.mainloop()
def log():
    base = Tk()
    base.geometry("500x500")
    lb2= Label(base, text="Enter username:", width=13,font=("arial",12))
    lb2.place(x=20,y=120)
    user=StringVar()
    en5=Entry(base,textvariable=user)
    en5.place(x=200, y=120)
    lb6= Label(base, text="Enter Password:", width=13,font=("arial",12))
    lb6.place(x=20, y=160)
    passw=StringVar()
    en6= Entry(base,textvariable=passw,show="*")
    en6.place(x=200, y=160)
    verifying=partial(verify,user,passw)
    log=Button(base, text="Login",command=verifying, width=10)
    log.place(x=200,y=180)
    lb3=Label(base,text="Not an existing user?",width=16,font=("arial",12))
    lb3.place(x=130,y=220)
    reg_b=Button(base,text="Register",command=reg,width=10,font=("arial",8))
    reg_b.place(x=290,y=220)
    base.mainloop()
def verify(username,password):
    conn = mysql.connector.connect(user='root', password='Karthi23', host='127.0.0.1', database='sks')
    cursor=conn.cursor()
    query="select Username,Password from sks.DETAILS"
    cursor.execute(query)
    res=cursor.fetchone()
    vals=(username.get(),password.get())
    if res[0]!=vals[0]:
        tm.showerror("Invalid Username or Password")
    else:
        base_1=Tk()
        ls= Label(base_1, text="Login Successful", width=13,font=("arial",12))
        ls.place(x=20,y=120)
        proceed=Button(base_1,text="Proceed",width=10)
        proceed.place(x=20,y=135)
    conn.close()
def insert(name,mail,ph_no,gender,username,password):
    conn = mysql.connector.connect(user='root', password='Karthi23', host='127.0.0.1', database='sks')
    cursor=conn.cursor()
    query="INSERT INTO sks.DETAILS (NAME,EMAIL,CONTACT_NUMBER,GENDER,USERNAME,PASSWORD)VALUES(%s,%s,%d,%d,%s,%s)"
    vals=(name.get(),mail.get(),int(ph_no.get()),gender.get(),username.get(),password.get())
    #cursor.execute(query,vals)
    print("Registered successfully.")
    conn.close()
log()
